name: Bun CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [windows-latest, macOS-latest, ubuntu-latest]
                bun: [latest]

        steps:
            - uses: actions/checkout@v4
            - name: Use Bun ${{ matrix.bun }} ${{ matrix.os }}
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: ${{ matrix.bun }}
            - name: bun install, build, and test
              run: |
                  bun install
                  bun run --bun test
              env:
                  CI: true
