name: ci-bun

on:
    push:
        branches:
            - main

    pull_request:
        branches:
            - main

jobs:
    ci-bun:
        uses: eslint/workflows/.github/workflows/ci-bun.yml@3030377848e4c0b9c28a271b88a5c8c57359da68 # main
